name: Draft PDF

on:
  push:
    paths:
      - paper.md
      - paper.bib
      - images/Lextract_Workflow_Diagram.png
      - .github/workflows/draft-pdf.yml

permissions:
  contents: write

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout branch (not detached)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0 

      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: paper.md

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper.pdf

      - name: Commit PDF to repository
        uses: EndBug/add-and-commit@v9
        with:
          message: "(auto) Paper PDF Draft"
          add: "paper.pdf"
          # optional, but keeps authorship tidy:
          author_name: shriyanyamali
          author_email: shriyanyamali@users.noreply.github.com
